### ISSUE TITLE
building all-pdf

### ISSUE THREAD

**Issue by zsiki** [opengisch/QField-docs#3]
After adding Hungarian language to the Makefile I was able to build html docs. 
When I tried to build all-pdf it failed.  I use Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
The log message:

```
# Sphinx version: 1.3.6
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   index
#   installation-guide/index
#   concepts/index
#   project-management/index
#   project-management/dataformat
#   user-guide/index
#   development/index
#   
#   resolving references...
#   writing...
# Loaded extensions:
#   vimeo (unknown version) from /home/siki/QField-docs/_ext/vimeo.pyc
#   alabaster (0.7.7) from /usr/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   edit_on_github (unknown version) from /home/siki/QField-docs/_ext/edit_on_github.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 267, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/latex.py", line 118, in write
    docwriter.write(doctree, destination)
  File "/usr/lib/python2.7/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python2.7/dist-packages/sphinx/writers/latex.py", line 110, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/lib/python2.7/dist-packages/sphinx/writers/latex.py", line 2015, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: vimeo
```

**Comment by m-kuhn** [comment]
Looks like it's unable to handle the `vimeo` directive. For this to work in HTML [I had to add an extension](https://github.com/opengisch/QField-docs/blob/master/_ext/vimeo.py), I guess it would be required to do something similar.

Apart from this, I found it quite tedious to maintain the pdf output (it would sometimes fail for non-latin1 characters etc), that's why it's currently disabled.

If someone wants to revive it, please go ahead :+1:

**Comment by zsiki** [comment]
Thanks,
unfortunately actually  I have no time to revive it :(

**Comment by m-kuhn** [comment]
We can still leave it open and hope for someone to jump in

**Comment by mbernasocchi** [comment]
for reference it is not only vimeos, it is also the gif files that break the build

**Comment by marioba** [comment]
I am closing this because in the meantime the structure of the documentation has completely changed.
